-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS
WHERE NAME LIKE 'Lucy' or NAME LIKE 'Ella' or 
NAME LIKE 'Pickle' or NAME LIKE 'Rogan' or
NAME LIKE 'Sabrina' or NAME LIKE 'Mitty'
ORDER BY ANIMAL_ID;